packages:
  - .

allowBuilds:
  esbuild: set this to true or false
  react-vertical-timeline-component: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false

onlyBuiltDependencies:
  - esbuild
  - react-vertical-timeline-component
  - sharp
  - workerd
