name: Pull Request
on:
    pull_request:
        types: [opened, reopened, synchronize, edited]
permissions:
    contents: read
    actions: write

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - name: Install Playwright browsers
              run: pnpm exec playwright install --with-deps
            - name: Run Playwright tests
              run: pnpm test:e2e
            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report
                  retention-days: 7
                  if-no-files-found: warn
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run typecheck


